spring.profiles.include:
  - common
  - domain

spring:
  application:
    name: blog-service

feign:
  hystrix:
    enabled: true
  kakao-api:
    url: dapi.kakao.com
    rest-api-key: a20ec78848ce4ecd73ee5c3c299f2fb4
  naver-api:
    url: https://openapi.naver.com
    client-id: V9HvuF3xpQU2pG5zEpmb
    client-secret: l3sjjIpgO1
