spring.profiles.include:
  - common
  - domain

spring:
  profiles:
    active: local
  application:
    name: blog-service
  redis:
    host: localhost
    port: 6379

feign:
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
  kakao-api:
    url: dapi.kakao.com
    rest-api-key: a20ec78848ce4ecd73ee5c3c299f2fb4
  naver-api:
    url: https://openapi.naver.com
    client-id: V9HvuF3xpQU2pG5zEpmb
    client-secret: l3sjjIpgO1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 30000

